### PR TITLE
Adds composer.json

### PR DESCRIPTION
**Pull request by aschrammel**

### CODE REVIEW

**Comment by avoelkl** [comment]
👍

**Comment by astorm** [comment]
Thanks for the prompting @aschrammel and @avoelkl.  Merged, and then updated to use the name `pulsestorm/cross-area-session`.

If you both have a moment -- how are you using composer and M1 together?  Is there a specific project you're using to symlink or copy thing over to app/code from vendor?  Or are you using custom scripts for that?

**Comment by avoelkl** [comment]
Hi Alan,

We're using M1 with a Magento Composer Module like
https://github.com/magento-hackathon/composer-repository or
https://github.com/bragento/bragento-composer-installer.

The code is retrieved via a git repo as well (for example https://github.com/bragento/magento-core) and the modules are symlinked into the core.

For your specific module: We're refactoring a project from a non-composer to a composer setup where we found this module in use, so we added (needed) a composer.json.

Let me know if you have further questions on our setup.

**Comment by astorm** [comment]
> We're using M1 with a Magento Composer Module like

Which specific module are you using? `bragento/bragento-composer-installer`? `magento-hackathon/composer-repository`?  Or your own?

**Comment by avoelkl** [comment]
Currently we use `bragento/bragento-composer-installer`.
I've used `magento-hackathon/composer-repository` and also `aoepeople/composer-installers` before.

I am not a Magento Composer installer expert so I cannot comment too much on the pros and cons of the various modules.

**Comment by avoelkl** [comment]
This is also interesting to use with Magento & Composer:
https://packages.firegento.com/

**Pull request merged**
